source: {type: video, camera_index: 0, video_path: data/hirsiz.mp4}
model: {hand_path: runs/el_modelim_v1-7/weights/best.pt, hand_threshold: 0.35, pose_path: yolo26x-pose.pt}
classes: {el: KRITIK}
pose: {proximity_ratio_threshold: 0.35, hand_match_radius_ratio: 0.25}
rules: {cooldown_seconds: 3.0, debounce_seconds: 5.0}
performance: {target_fps: 15, min_fps: 5}
database: {path: data/olaylar.db}
zones:
  etkilesim:
  - [381, 124]
  - [386, 300]
  - [390, 398]
  - [525, 395]
  - [490, 128]
  - [382, 126]
  kasa:
  - [488, 313]
  - [504, 393]
  - [566, 390]
  - [548, 313]
  - [497, 312]
  tehlike:
  - [565, 387]
  - [613, 391]
  - [593, 299]
  - [563, 128]
  - [494, 131]
  - [517, 302]
  - [545, 306]
  - [566, 381]
